name: CI/CD Pipeline
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt --prefer-binary --disable-pip-version-check

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image
        run: |
          IMAGE_TAG=${{ github.sha }}

          docker buildx build \
            --platform linux/amd64 \
            --provenance=false \
            --cache-from=type=gha \
            --cache-to=type=gha,mode=max \
            -t 553004107808.dkr.ecr.us-east-1.amazonaws.com/lambda-container:$IMAGE_TAG \
            -t 553004107808.dkr.ecr.us-east-1.amazonaws.com/lambda-container:latest \
            --push .

  test:
    if: false
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt --prefer-binary --disable-pip-version-check
          pip install pytest

      - name: Run tests
        run: pytest
    
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "21"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
    
      - name: Install Serverless Framework
        run: npm install -g serverless@3

      - name: Deploy to AWS
        run: serverless deploy --stage prod
        env:
          DATA_BASE_URL: ${{ secrets.DATA_BASE_URL }}
          SECRET_JWT_PRIVATE_KEY: ${{ secrets.SECRET_JWT_PRIVATE_KEY }}
          SECRET_JWT_PUBLIC_KEY: ${{ secrets.SECRET_JWT_PUBLIC_KEY }}
          ECR_IMAGE_URI: ${{ secrets.ECR_IMAGE_URI }}
